name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          path: 'QDash-source'

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV

      - name: Package artifacts properly
        shell: bash
        run: |
          mv ${{ github.workspace }}/QDash-source QDash-${{ env.VERSION }}
          ls
          echo
          echo
          ls *
          echo
          echo

          for arch in amd64 aarch64
          do
            mv QDash-Linux-Binary*${arch}/QDash.tar.zst QDash-Linux-${{ env.VERSION }}-$arch.tar.zst
            mv QDash*${arch}.AppImage/*.AppImage QDash-Linux-${{ env.VERSION }}-${arch}.AppImage

            mv QDash-Windows-Setup*${arch}/QDash* QDash-Windows-Setup-${{ env.VERSION }}-${arch}.exe
            zip -r QDash-Windows-Portable-${{ env.VERSION }}-${arch}.zip QDash-Windows-Portable*${arch}/*
          done

          mv QDash-macOS*/QDash.tar.gz QDash-macOS-${{ env.VERSION }}-universal.tar.gz
          zip QDash-macOS-${{ env.VERSION }}-universal.zip QDash-macOS-${{ env.VERSION }}-universal.tar.gz

          tar -czf QDash-${{ env.VERSION }}.tar.gz QDash-${{ env.VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: QDash ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: |
            QDash-${{ env.VERSION }}.tar.gz

            QDash-Linux-${{ env.VERSION }}-amd64.tar.zst
            QDash-Linux-${{ env.VERSION }}-aarch64.tar.zst
            QDash-Linux-${{ env.VERSION }}-amd64.AppImage
            QDash-Linux-${{ env.VERSION }}-aarch64.AppImage

            QDash-Windows-Portable-${{ env.VERSION }}-amd64.zip
            QDash-Windows-Portable-${{ env.VERSION }}-aarch64.zip
            QDash-Windows-Setup-${{ env.VERSION }}-amd64.exe
            QDash-Windows-Setup-${{ env.VERSION }}-aarch64.exe

            QDash-macOS-${{ env.VERSION }}-universal.zip
