name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: MinSizeRel

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          path: 'QDash-source'

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV

      - name: Package artifacts properly
        shell: bash
        run: |
          mv ${{ github.workspace }}/QDash-source QDash-${{ env.VERSION }}

          mkdir -p artifacts

          for arch in amd64 aarch64
          do
            mv linux-appimage-$arch/* artifacts
            mv linux-binary-$arch/QDash.tar.zst artifacts/QDash-Linux-${{ env.VERSION }}-$arch.tar.zst
          done

          for arch in amd64 arm64
            mv windows-$arch/* artifacts
            mv windows-setup-$arch/QDash-Setup.exe artifacts/QDash-Windows-${{ env.VERSION }}-$arch.exe
          done

          mv macos-universal/QDash.tar.gz .
          zip artifacts/QDash-macOS-${{ env.VERSION }}-universal.zip QDash.tar.gz

          tar -czf QDash-Source-${{ env.VERSION }}.tar.gz QDash-${{ env.VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: QDash ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: artifacts/*